# Generated by Django 5.1.3 on 2024-12-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0006_filemodel_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_format',
            field=models.CharField(default='pdf', max_length=20, verbose_name='Format'),
        ),
    ]
