# Generated by Django 5.1.3 on 2024-12-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0007_alter_filemodel_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='output_file_url',
            field=models.CharField(default='http://127.0.0.1:8000/media/files/converted_files/output.xxx', max_length=200),
        ),
    ]
