# Generated by Django 5.1.3 on 2024-12-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0008_filemodel_output_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='output_file_url',
        ),
    ]
