# Generated by Django 5.1.4 on 2024-12-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0009_remove_filemodel_output_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_format',
            field=models.CharField(max_length=20, null=True, verbose_name='Format'),
        ),
    ]
