# Generated by Django 5.1.4 on 2025-02-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0010_alter_filemodel_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='request_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
