services:
  nginx:
    build:
      context: .
      image: nginx
    container_name: nginx
    volumes:
      - ./config_nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config_nginx/available.conf:/etc/nginx/conf.d/available.conf
      - ./config_nginx/blaclist.conf:/app/blacklist.conf
      - ./config_nginx/blaclist.txt:/app/blacklist.txt
      - ./dist:/usr/share/nginx/html:ro
      - ../logs/nginx:/var/log/nginx

    ports:
      - "80:80"
    restart: unless-stopped
# COPY config_nginx/nginx.conf /etc/nginx/nginx.conf
# COPY config_nginx/available.conf /etc/nginx/conf.d/available.conf
# COPY config_nginx/blaclist.txt /app
# COPY config_nginx/blaclist.conf /app