services:
  nginx:
    build:
      context: .
    image: nginx
    container_name: nginx
    volumes:
      - ./config_nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config_nginx/available.conf:/etc/nginx/conf.d/available.conf
      - ./config_nginx/blacklist.conf:/app/blacklist.conf
      - ./config_nginx/blacklist.txt:/app/blacklist.txt
      - ./dist:/usr/share/nginx/html:ro
      - ../logs/nginx:/var/log/nginx

    ports:
      - "80:80"
    restart: unless-stopped
